/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package helloworld

import org.assertj.core.api.Assertions.assertThat
import org.junit.Test
/*
    - 입력된 수가 짝수라면 2로 나눈다.
    - 입력된 수가 홀수라면 3을 곱하고 1을 더한다
    - 1이 나올때 까지 위의 작업을 계속한다.
    - 위의 작업을 센다.
*/

fun solution(n : Int) : Int {
    return recursive(n,0)
}

fun recursive(n : Int, count : Int) : Int {

    return when {
        n == 1 -> {
            return count
        }
        n % 2 == 0 -> {
            recursive(n / 2, count + 1);
        }
        else -> {
            recursive((n * 3) + 1, count + 1)
        }
    }

}

class SolutionTest {

    @Test
    fun `Find How much should call collatz function to get number one`() {
        assertThat(solution(6)).isEqualTo(8);
        assertThat(solution(16)).isEqualTo(4);
    }
}

