/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ironstick

import org.junit.Test
import org.assertj.core.api.Assertions.assertThat

fun solution(value: String): Int {
    val stick = value.replace("()", "0", false)

    tailrec fun recursive(stick: String, index: Int, stickCount: Int, result: Int): Int {
        if(stick.length === index) {
            return result
        }
        println(stick[index])

        return when (stick[index]){
            '(' -> recursive(stick, index+1, stickCount+1, result)
            '0' -> recursive(stick, index+1, stickCount, result+stickCount)
            else -> recursive(stick, index+1, stickCount-1, result+1)

        }
    }
    return recursive(stick,0,0,0)
}
class IronStick {
    @Test
    fun `Get cut Piece counts from iron stick`() {
        assertThat(solution("(()())")).isEqualTo(3)
        assertThat(solution("()")).isEqualTo(0)
        assertThat(solution("()(((()())(())()))(())")).isEqualTo(17)
    }
}
