/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.yh.phonebook

import kotlin.test.Test
import kotlin.test.assertNotNull
import org.assertj.core.api.Assertions.assertThat
/*
 - 작은 수 순서대로 정렬한다.
 - 순회하면서 자신이 startsWith를 사용하여 값이 존재하는지 찾고 있으면 false를 리턴
 - 없으면 true를 리턴
*/
fun solution (arr :Array<String>) : Boolean {

    val sortedArr = arr.map {Integer.parseInt(it)}.sorted().map {it.toString()}
    var i = 0
    sortedArr.any { sortedArr.drop(i+1).any { it.startsWith(sortedArr[i]) } }
    return !sortedArr.any { sortedArr.drop(i+1).any { it.startsWith(sortedArr[i]) } }
}

class Test {
    @Test fun `Check whether there is an element that is prefix for other elements `() {
        assertThat(solution(arrayOf("119", "97674223", "1195524421"))).isEqualTo(false)
        assertThat(solution(arrayOf("123","456","789"))).isEqualTo(true)
        assertThat(solution(arrayOf("12","123","1235","567","88"))).isEqualTo(false)
    }
}
